carz:
  app:
    name: 'DriftCarz'
    scheduler:
      auto:
        expression: '* * * * *'

server:
  port: 8088

spring:
  datasource:
    url: jdbc:h2:mem:drifCarzDb
    driverClassName: org.h2.Driver
    userName: admin
    password: admin@123%456
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2